### ISSUE TITLE
GUI web - the box containing the map does not adapt to the reduction of the page

### ISSUE THREAD

**Issue by killertag** [IngSW-unipv/Progetto-G20#1]
**Describe the bug**
italian version
il box che contiene la mappa non si adatta alla pagina soprattutto alla riduzione.

**To Reproduce**
- per simulare il bug basta ridurre la pagina in larghezza  a dimensioni tablet/ smartphone oppure visualizzare la pagina web da smartphone.

**Expected behavior**
- aggiungere una modifica al box al raggiungimento di una determinata larghezza in pixel da fare in automatico @media screen and (px)

**Screenshots**
<a href="https://ibb.co/Jy45638"><img src="https://i.ibb.co/RBmzrjt/box-mappa.png" alt="box-mappa" border="0"></a>
[https://ibb.co/Jy45638](url)

**Comment by AltamoreAndreaUni** [comment]
we have to add a css, related to maps' iframe, with dimensions expressed as auto or some percentual.
